# Generated by Django 4.2.6 on 2023-11-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_alter_habit_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_to_perform',
            field=models.CharField(verbose_name='Время на выполнение'),
        ),
    ]
